using System.Collections;
using UnityEngine;
using UnityEngine.Networking;

public class PoemManager : MonoBehaviour
{
    string[] splitter = { " ", "\n", "," };

    // Words to find generated by Gemini API
    [SerializeField]
    string[] wordsToFind;

    // Button to collect words of poem
    [SerializeField]
    GameObject[] wordButtonsToCollect;

    int curWordId;
    string curWordToCollect;

    private void Start()
    {
        GeminiAPIManager.instance.OnWordsGenerated += OnWordsGenerated;
    }

    private void OnWordsGenerated(string wordResult)
    {
        wordsToFind = wordResult.Split(splitter, System.StringSplitOptions.RemoveEmptyEntries);

        SetupWordsToCollect();
    }

    //Set up generated words in UI buttons
    void SetupWordsToCollect()
    {
        curWordId = 0;
        curWordToCollect = wordsToFind[curWordId];
        for (int i = 0; i < wordsToFind.Length; i++)
        {
            wordButtonsToCollect[i].GetComponentInChildren<TMPro.TextMeshProUGUI>().text = wordsToFind[i];
        }
    }

    // Click on each words to collect
    public void CollectCurWord()
    {
        wordButtonsToCollect[curWordId].GetComponent<UnityEngine.UI.Button>().interactable = false;
        if (curWordId < wordsToFind.Length - 1)
        {
            curWordId++;
            curWordToCollect = wordsToFind[curWordId];
        }
        else
        {
            Debug.Log("All Words Collected!");
        }
    }
}
